name: Oracle Cloud Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' 

jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install oci python-dotenv pyTelegramBotAPI

      - name: Create OCI Config and Key
        run: |
          # Создаем файлы в корне
          echo "${{ secrets.OCI_KEY_CONTENT }}" > key.pem
          chmod 600 key.pem
          
          echo "[DEFAULT]" > config
          echo "user=${{ secrets.OCI_USER_ID }}" >> config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> config
          echo "tenancy=${{ secrets.OCI_TENANCY_ID }}" >> config
          echo "region=eu-amsterdam-1" >> config
          echo "key_file=$(pwd)/key.pem" >> config
          
          # Копируем их внутрь папки со скриптом, чтобы bot.py их увидел
          mkdir -p "Ampere 24 ram 4 cpu"
          cp config "Ampere 24 ram 4 cpu/config"
          cp key.pem "Ampere 24 ram 4 cpu/key.pem"

      - name: Run Hunter Script
        env:
          AVAILABILITY_DOMAINS: "bJxe:eu-amsterdam-1-AD-1"
          DISPLAY_NAME: "Oracle-ARM-Server"
          COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          SSH_AUTHORIZED_KEYS: ${{ secrets.SSH_PUBLIC_KEY }}
          IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          BOOT_VOLUME_SIZE_IN_GBS: 50
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          UID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OCPUS: 4
          MEMORY_IN_GBS: 24
          MINIMUM_TIME_INTERVAL: 1
          OCI_REGION: "eu-amsterdam-1"
        run: python "Ampere 24 ram 4 cpu/bot.py"
