name: Oracle Cloud Hunter

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' 

jobs:
  hunt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install oci python-dotenv pyTelegramBotAPI

      - name: Create OCI Config and Key
        run: |
       
          echo "${{ secrets.OCI_KEY_CONTENT }}" > key.pem
          chmod 600 key.pem
          
        
          echo "[DEFAULT]" > config
          echo "user=${{ secrets.OCI_USER_ID }}" >> config
          echo "fingerprint=${{ secrets.OCI_FINGERPRINT }}" >> config
          echo "tenancy=${{ secrets.OCI_TENANCY_ID }}" >> config
          echo "region=${{ secrets.OCI_REGION }}" >> config
          echo "key_file=$(pwd)/key.pem" >> config

      - name: Run Hunter Script
        env:
          AVAILABILITY_DOMAINS: ${{ secrets.AVAILABILITY_DOMAINS }}
          DISPLAY_NAME: "Oracle-ARM-Server"
          COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }} 
          SUBNET_ID: ${{ secrets.SUBNET_ID }}
          SSH_AUTHORIZED_KEYS: ${{ secrets.SSH_PUBLIC_KEY }}
          IMAGE_ID: ${{ secrets.IMAGE_ID }}
          BOOT_VOLUME_SIZE_IN_GBS: 50
          BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          UID: ${{ secrets.TELEGRAM_CHAT_ID }}
          OCPUS: 4
          MEMORY_IN_GBS: 24
          MINIMUM_TIME_INTERVAL: 1
        run: python "Ampere 24 ram 4 cpu/bot.py"
